manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: m165437
      url-base: https://github.com/M165437
    - name: jdramirezl
      url-base: https://github.com/jdramirezl
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: nice-view-gem-jdramirezl
      remote: jdramirezl
      revision: main
  self:
    path: config  

